### ISSUE TITLE
登陆后在内部看番可能导致账号异常

### ISSUE THREAD

**Issue by WhiverFichos** [10miaomiao/bilimiao2#1]
大概是没有进 epxxx 直接在 av 播放的结果。
如果修不了的话加个提示吧……别有后人再栽跟头……
————————————————————————
虽然不敢不用外部播放器了，登录时如果需要手机或邮箱验证码是加载不出来的。（另一个每次登录都需要验证码的账号）
————————————————————————
PS. preference_setting 中的半角标点让强迫症十分不爽 →_→（……，！）
————————————————————————
感谢时光机，我青回 (｡･∀･)ﾉ

**Comment by 10miaomiao** [comment]
原来封号是这个原因吗，我有空试一下，新版本我加了网页登录（已上传到酷安，github还没有更新）
