### ISSUE TITLE
时光机是依靠B站的哪个api？

### ISSUE THREAD

**Issue by mutonix** [10miaomiao/bilimiao2#148]
我想找到比较多b站分区过去的视频，时光机的功能很好，但是一个个人工点有点慢，请问是用b站哪个api获取的？十分感谢！

**Comment by 10miaomiao** [comment]
1、旧web端api（目前bilimiao使用的）：
>  https://s.search.bilibili.com/cate/search

*请求方式：GET*
认证方式：无需认证

**url参数：**
| 参数名   | 类型 | 内容                   | 必要性 | 备注 |
| -------- | ---- | ---------------------- | ------ | ---- |
| main_ver| str  | 固定“v3” | 必要   |      |
| search_type| str  | 固定“video” | 必要   |      |
| view_type| str  | 固定“hot_rank” | 必要   |      |
| copy_right| str  | 固定“-1” | 必要   |      |
| cate_id| num| 分区id| 必要   |      |
| order| str | 排序方式| 必要   |可选：click,scores,stow,coin,dm|
| page| num| 页码| 必要   |      |
| pagesize| num| 每页数量| 必要   |      |
| time_from| str | 起始时间| 必要   | 格式：YYYYMMDD|
| time_to| str | 结束时间| 必要   | 格式：YYYYMMDD |

**示例：**
>  https://s.search.bilibili.com/cate/search?main_ver=v3&search_type=video&view_type=hot_rank&copy_right=-1&order=click&cate_id=24&page=1&pagesize=30&time_from=20240525&time_to=20240624

[bilimiao代码](https://github.com/10miaomiao/bilimiao2/blob/master/bilimiao-comm/src/main/java/com/a10miaomiao/bilimiao/comm/apis/RegionAPI.kt)

2、新web端api：
> https://api.bilibili.com/x/web-interface/newlist_rank

*请求方式：GET*
认证方式：无需认证
**url参数：**
参考上表
**示例：**
> https://api.bilibili.com/x/web-interface/newlist_rank?main_ver=v3&search_type=video&view_type=hot_rank&copy_right=-1&new_web_tag=1&order=click&cate_id=24&page=1&pagesize=30&time_from=20240525&time_to=20240624

[B站mad区](https://www.bilibili.com/v/douga/mad)往下滚动，近期投稿就是，可以自己用浏览器抓包试试。

3、APP端搜索API，支持时间范围，但需加搜索关键字
> bilibili.polymer.app.search.v1.SearchAll

**参考：**
[bilimiao](https://github.com/10miaomiao/bilimiao2/blob/master/bilimiao-comm/src/main/proto/bilibili/polymer/app/search/v1/search.proto)
[bilibili-API-collect](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/grpc_api/bilibili/polymer/app/search/v1/search.proto)

无示例
