### ISSUE TITLE
[bug] 搜索功能异常

### ISSUE THREAD

**Issue by tylvn** [10miaomiao/bilimiao2#15]
在 Huawei Mate 30 用 Gboard 输入时无法正常搜索。

https://user-images.githubusercontent.com/95011132/188632948-95bdd4f1-2512-4de9-bc02-45579bef80b4.mp4

**Comment by yu22c** [comment]
试试删掉视频屏蔽规则？
我也有这个bug

**Comment by tylvn** [comment]
该 bug 已消失
