### ISSUE TITLE
从网页打开客户端时崩溃(手机同时有官方和bilimiao)

### ISSUE THREAD

**Issue by Phuehvk** [10miaomiao/bilimiao2#158]
>>>>时间: 2024-07-30 02:09:47
设备型号: 23116PN5BC
设备品牌: shennong
硬件名称: qcom
硬件制造商: Xiaomi
系统版本: 14
系统版本号: 34
应用版本: 2.3.8.3
应用版本号: 103

异常类: class java.lang.IllegalStateException
异常信息: Fragment VideoInfoFragment{e0871f5} (3616fb93-b3b8-4e14-8274-d3163370ab37) not attached to an activity.

****堆栈追踪 1
类名: androidx.fragment.app.Fragment
方法: requireActivity
文件: Fragment.java
行数: 1000

****堆栈追踪 2
类名: com.a10miaomiao.bilimiao.page.video.VideoInfoViewModel$autoStartPlay$1
方法: invokeSuspend
文件: VideoInfoViewModel.kt
行数: 177

****堆栈追踪 3
类名: kotlin.coroutines.jvm.internal.BaseContinuationImpl
方法: resumeWith
文件: ContinuationImpl.kt
行数: 33

****堆栈追踪 4
类名: kotlinx.coroutines.internal.DispatchedContinuationKt
方法: resumeCancellableWith
文件: DispatchedContinuation.kt
行数: 367

****堆栈追踪 5
类名: kotlinx.coroutines.intrinsics.CancellableKt
方法: startCoroutineCancellable
文件: Cancellable.kt
行数: 30

****堆栈追踪 6
类名: kotlinx.coroutines.intrinsics.CancellableKt
方法: startCoroutineCancellable$default
文件: Cancellable.kt
行数: 25

****堆栈追踪 7
类名: kotlinx.coroutines.CoroutineStart
方法: invoke
文件: CoroutineStart.kt
行数: 110

****堆栈追踪 8
类名: kotlinx.coroutines.AbstractCoroutine
方法: start
文件: AbstractCoroutine.kt
行数: 126

****堆栈追踪 9
类名: kotlinx.coroutines.BuildersKt__Builders_commonKt
方法: launch
文件: Builders.common.kt
行数: 56

****堆栈追踪 10
类名: kotlinx.coroutines.BuildersKt
方法: launch
文件: null
行数: 1

****堆栈追踪 11
类名: kotlinx.coroutines.BuildersKt__Builders_commonKt
方法: launch$default
文件: Builders.common.kt
行数: 47

****堆栈追踪 12
类名: kotlinx.coroutines.BuildersKt
方法: launch$default
文件: null
行数: 1

****堆栈追踪 13
类名: com.a10miaomiao.bilimiao.page.video.VideoInfoViewModel
方法: autoStartPlay
文件: VideoInfoViewModel.kt
行数: 172

****堆栈追踪 14
类名: com.a10miaomiao.bilimiao.page.video.VideoInfoViewModel
方法: access$autoStartPlay
文件: VideoInfoViewModel.kt
行数: 43

****堆栈追踪 15
类名: com.a10miaomiao.bilimiao.page.video.VideoInfoViewModel$loadData$1$3
方法: invokeSuspend
文件: VideoInfoViewModel.kt
行数: 150

****堆栈追踪 16
类名: kotlin.coroutines.jvm.internal.BaseContinuationImpl
方法: resumeWith
文件: ContinuationImpl.kt
行数: 33

****堆栈追踪 17
类名: kotlinx.coroutines.DispatchedTask
方法: run
文件: DispatchedTask.kt
行数: 108

****堆栈追踪 18
类名: android.os.Handler
方法: handleCallback
文件: Handler.java
行数: 958

****堆栈追踪 19
类名: android.os.Handler
方法: dispatchMessage
文件: Handler.java
行数: 99

****堆栈追踪 20
类名: android.os.Looper
方法: loopOnce
文件: Looper.java
行数: 224

****堆栈追踪 21
类名: android.os.Looper
方法: loop
文件: Looper.java
行数: 318

****堆栈追踪 22
类名: android.app.ActivityThread
方法: main
文件: ActivityThread.java
行数: 8677

****堆栈追踪 23
类名: java.lang.reflect.Method
方法: invoke
文件: Method.java
行数: -2

****堆栈追踪 24
类名: com.android.internal.os.RuntimeInit$MethodAndArgsCaller
方法: run
文件: RuntimeInit.java
行数: 561

****堆栈追踪 25
类名: com.android.internal.os.ZygoteInit
方法: main
文件: ZygoteInit.java
行数: 1013

**Comment by Phuehvk** [comment]
看起来问题出在com.a10miaomiao.bilimiao.page.video.VideoInfoViewModel这个类下面的方法

**Comment by 10miaomiao** [comment]
已修复
