### ISSUE TITLE
[有录像]    “自动恢复进度”引起的视频循环加载

### ISSUE THREAD

**Issue by sun3420** [10miaomiao/bilimiao2#167]
视频播放结束后由于有自动恢复进度，会自动跳转到最后一秒，然后循环，好像没有“播完暂停”的功能

这样的话循环播放好像也不行了诶

这是录像   :-D
https://github.com/user-attachments/assets/8a8fff90-bded-4221-9ee6-271052f770bf

**Comment by 10miaomiao** [comment]
已修复
