### ISSUE TITLE
在网页登录里，填写验证码并确认后，显示请使用最新版本扫码登录

### ISSUE THREAD

**Issue by yellow-plum** [10miaomiao/bilimiao2#173]
![Screenshot_20240920-210854](https://github.com/user-attachments/assets/c29f7760-87a4-4d92-bdc7-53aba326fa77)
设备：pixel 7 pro
系统：android 14
就是卡在这里了，以前一直可以用的，这段时间尝试很多次还是无法登录。想问问有什么解决方案

**Comment by 10miaomiao** [comment]
网页登录暂不可用，请用其它方式登录

**Comment by yellow-plum** [comment]
> 网页登录暂不可用，请用其它方式登录

感谢您的回复
