### ISSUE TITLE
突然崩溃

### ISSUE THREAD

**Issue by lowboss** [10miaomiao/bilimiao2#176]
大约于2024.10.16上午9时后我的所有设备上的bilimiao均无法打开，在弹出错误日志后会反复自动重启软件
使用版本：2.3.9/2.3.10

**Comment by lowboss** [comment]
![Uploading screenshot_20241016_092449.jpg…]()

**Comment by vvvvran** [comment]
我也是

**Comment by lowboss** [comment]
![screenshot_20241016_092449](https://github.com/user-attachments/assets/39825b31-50cf-40ef-a9f5-332474406bbc)

**Comment by 10miaomiao** [comment]
抱歉，建议先关闭APP，然后把系统时间改为明天，然后再打开APP，如果正常就可以改回系统时间了

**Comment by lowboss** [comment]
已解决



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月16日 09:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [10miaomiao/bilimiao2] 突然崩溃 (Issue #176) |

抱歉，建议先关闭APP，然后把系统时间改为明天，然后再打开APP，如果正常就可以改回系统时间了
