### ISSUE TITLE
希望可以添加倍速播放

### ISSUE THREAD

**Issue by tylvn** [10miaomiao/bilimiao2#3]
希望可以添加**倍速播放**功能，要是能像 [Video Speed Controller](https://github.com/igrigorik/videospeed) 一样自由调节就更好了。

**Comment by silivers** [comment]
臣附议

**Comment by anni233** [comment]
倍速是灵魂臣附议

**Comment by xz-dev** [comment]
已添加基本的倍速功能，自定义部分待他人实现
https://github.com/10miaomiao/bilimiao2/pull/8
![Screenshot_20220807-001005_bilimiao](https://user-images.githubusercontent.com/32761048/183257099-3e14192b-2df0-4dd4-b467-805b1e27b364.png)

**Comment by tylvn** [comment]
> 已添加基本的倍速功能，自定义部分待他人实现 
>
> ![Screenshot_20220807-001005_bilimiao](https://user-images.githubusercontent.com/32761048/183257099-3e14192b-2df0-4dd4-b467-805b1e27b364.png)

期待在新的更新中能看到该功能的实现👍
