### ISSUE TITLE
增加弹幕调整设置

### ISSUE THREAD

**Issue by amokiel** [10miaomiao/bilimiao2#34]
各方面体验都挺不错的，弹幕设置稍微有点不太够用。弹幕密度有点太大，希望可以设置屏幕的50%或者25%显示弹幕，目前总是全屏显示所有弹幕，弹幕确实有点多了，可以增强一些弹幕方面的功能，合并相同弹幕，减少弹幕密度之类的。其它基本上需要的功能都满足了，谢谢开发者，辛苦啦！

**Comment by 2584191127** [comment]
+1，另外希望有长按三倍速的功能
