### ISSUE TITLE
软件使用时遇到的蛋疼问题

### ISSUE THREAD

**Issue by zhysgit** [10miaomiao/bilimiao2#39]
安卓6.1

处于视频界面时，手机无法息屏，哪怕视频已经暂停

![Screenshot_2023-06-08-18-18-36-160_com miui securitycenter](https://github.com/10miaomiao/bilimiao2/assets/35164194/51d5e6ed-74d1-4427-8129-24ece89a72a3)
手机屏幕亮了七个小时才发现

**Comment by 10miaomiao** [comment]
2.2.6版本已修复此问题
