### ISSUE TITLE
点击部分评论时会闪退

### ISSUE THREAD

**Issue by xyl23333** [10miaomiao/bilimiao2#4]
[https://www.toptal.com/developers/hastebin/upebuyuyir](https://www.toptal.com/developers/hastebin/upebuyuyir)

![Screenshot_20220416-131055.png](https://user-images.githubusercontent.com/46397979/163662536-6b93d32e-76ba-405a-a491-957f7838b553.png)
![Screenshot_20220416-131105.png](https://user-images.githubusercontent.com/46397979/163662540-6e4f5fce-d696-4024-9146-4f99ac42a80f.png)

**Comment by 10miaomiao** [comment]
2.1.1版本已修复
