### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [10miaomiao/bilimiao2#46]
请问我可以将应用发布到 F-Droid 吗？

**Comment by huippunopeus** [comment]
@10miaomiao 如果您有意向将软件上架到 F-Droid，@linsui 能提供必要的帮助和指导。

**Comment by 10miaomiao** [comment]
> 请问我可以将应用发布到 F-Droid 吗？

可以私聊我，我可以提供gitlab账号

**Comment by linsui** [comment]
不需要 gitlab 账号，主要是需要你同意，以及如果构建出问题需要你的帮助。:)

**Comment by 10miaomiao** [comment]
> 不需要 gitlab 账号，主要是需要你同意，以及如果构建出问题需要你的帮助。:)

好的，如果你需要我的帮助可以私聊我

**Comment by linsui** [comment]
请问 lib-decoder-av1-release.aar 是什么库？

**Comment by 10miaomiao** [comment]
> lib-decoder-av1-release.aar

https://github.com/androidx/media/tree/release/libraries/decoder_av1

**Comment by linsui** [comment]
请问极验库是必需的吗？这个库 com.geetest.sensebot:sensebot 不是开源库。

**Comment by 10miaomiao** [comment]
> 请问极验库是必需的吗？这个库 com.geetest.sensebot:sensebot 不是开源库。

登录时需要用到

**Comment by 10miaomiao** [comment]
> > 请问极验库是必需的吗？这个库 com.geetest.sensebot:sensebot 不是开源库。
> 
> 登录时需要用到

或者可以改用网页版的校验库

**Comment by linsui** [comment]
用网页端应该是可以的，我看到网页端验证的功能被去掉了，请问可以加一个 F-Droid flavor 使用网页登陆吗？

**Comment by 10miaomiao** [comment]
其它flavor可以保留极验吗，仅在F-Droid flavor去掉极验？

**Comment by linsui** [comment]
只在 F-Droid 的 flavor 去掉极验就行。如果极验只是一种登陆方式，去掉还可以用其他方式登陆，那影响不大，直接去掉就行。另外 baidu mobstat 也得去掉，它也不开源。

**Comment by linsui** [comment]
有很多，可以看看这些 https://gitlab.com/-/snippets/1896503#acceptable-analytics

**Comment by 10miaomiao** [comment]
> 有很多，可以看看这些 https://gitlab.com/-/snippets/1896503#acceptable-analytics

好的，谢谢，baidu mobstat 可以直接移除

**Comment by 10miaomiao** [comment]
已增加foss flavors，并移除baidu mobstat和极验SDK

**Comment by linsui** [comment]
感谢，我试试能不能打包

**Comment by 10miaomiao** [comment]
还有一个问题，我想要发布在F-Droid上的版本，使用我自己的签名，我需要做什么操作吗

**Comment by linsui** [comment]
那需要[可重复构建](https://f-droid.org/docs/Reproducible_Builds/)。我们要构建出完全相同的 apk。

**Comment by linsui** [comment]
这里比较困难的是 lib-decoder-av1-release.aar 也要可重复构建。所以我们得从相同的 commit 构建。

**Comment by linsui** [comment]
暂时忽略 lib-decoder-av1-release.aar 构建成功了。F-Droid 不允许使用 bintray 所以需要加个 patch 把 `me.panpf:sketch-gif:2.7.1` 解析到 maven central。

```kts
allprojects {
    configurations.all {
        resolutionStrategy.dependencySubstitution {
            substitute(module("me.panpf:sketch-gif:2.7.1")).using(module("io.github.panpf.sketch:sketch-gif:2.7.1"))
        }
    }
}
```

**Comment by 10miaomiao** [comment]
已用github action成功构建出一个版本
> https://github.com/10miaomiao/bilimiao2/releases/tag/2.3.8.3
foss flavor已移除lib-decoder-av1-release.aar，可以尝试在F-Droid上发布此版本

**Comment by 10miaomiao** [comment]
已用github action成功构建出一个版本

> https://github.com/10miaomiao/bilimiao2/releases/tag/2.3.8.3

foss flavor已移除lib-decoder-av1-release.aar，可以尝试在F-Droid上发布此版本，应该是支持可重复构建的

**Comment by linsui** [comment]
好，成功 :+1: 现在加个 fastlane 就行了。https://gitlab.com/-/snippets/1895688

**Comment by 10miaomiao** [comment]
已提交fastlane

**Comment by linsui** [comment]
大概过几天就会发布了，感谢帮助。我仍然希望带回 av1 支持，有什么计划吗？

**Comment by linsui** [comment]
已经发布

**Comment by 10miaomiao** [comment]
> 已经发布

好的，谢谢你(❁´◡`❁)

**Comment by 10miaomiao** [comment]
> 大概过几天就会发布了，感谢帮助。我仍然希望带回 av1 支持，有什么计划吗？

暂无计划，等有时间了再整整

**Comment by linsui** [comment]
好，感谢
