### ISSUE TITLE
当前视频播放完成后再次播放时自动定位视频结束点

### ISSUE THREAD

**Issue by hhrwebsize** [10miaomiao/bilimiao2#49]
点开一个视频，播放完成后点击重新播放，将会自动定位视频结束点，导致再次出现播放完成的页面，如果要重新播放，就必须在点击重新播放后点击弹出的自动定位的重新播放按钮，这样很麻烦，能不能修一下

**Comment by 10miaomiao** [comment]
新版本已限制上次播放时间在后10秒时，不自动继续播放
