### ISSUE TITLE
希望添加 删除收藏夹操作

### ISSUE THREAD

**Issue by ghost** [10miaomiao/bilimiao2#65]
![Screenshot_20231016-173533.png](https://github.com/10miaomiao/bilimiao2/assets/122200112/48caadf1-748a-46b4-8af7-9f21e3bd721f)

收藏夹 添加&移除视频 功能正常，收藏夹不可进行 新建&删除 操作。

用起来不太方便呢…

**Comment by 10miaomiao** [comment]
已支持
