### ISSUE TITLE
下载目录在哪里

### ISSUE THREAD

**Issue by dreampjk** [10miaomiao/bilimiao2#68]

**Comment by 10miaomiao** [comment]
视频下载文件夹为：/storage/emulated/
0/Android/data/
com.a10miaomiao.bilimiao/download 目录结构与B站官方客户端保持一致，可与B站官方客户端相互复制缓存文件
如需导出视频文件可使用BiliDownOut导出。
BiliDownOut：https://github.com/10miaomiao/bili-down-out
