### ISSUE TITLE
可以增加一个合集的功能吗

### ISSUE THREAD

**Issue by echoy6** [10miaomiao/bilimiao2#80]
有些教程类视频up主会弄一个合集，这样可以更方便找到想看的视频，或者可以up主所有投稿视频那里弄一个按发布时间排序
![Screenshot_20240113_225709](https://github.com/10miaomiao/bilimiao2/assets/150945319/d3f6d0da-4848-42bb-a8a4-d7bcb31370f8)
![Screenshot_2024_0113_230100](https://github.com/10miaomiao/bilimiao2/assets/150945319/c571b7ea-0bf4-47ff-8c53-283d2761ae2e)
非常感谢

**Comment by 10miaomiao** [comment]
已增加合集功能
